#!/bin/bash
#PBS -N spmv_strong_2d
#PBS -q short_cpuQ
#PBS -l walltime=06:00:00
#PBS -l select=16:ncpus=8:mpiprocs=8:mem=50gb
#PBS -o logs/strong_2d_output.log
#PBS -e logs/strong_2d_error.log

# Load modules
module purge
module load gcc91
module load mpich-3.2.1--gcc-9.1.0

# Submission directory
cd $PBS_O_WORKDIR

# Create log directory
mkdir -p logs

# Ensure that the execution script is executable
# ASUMIENDO QUE EL SCRIPT SE LLAMA: run_2d_strong_scaling.sh
chmod +x ./sh/run_2d_strong_scaling.sh

# Execute
./sh/run_2d_strong_scaling.sh