#!/bin/bash
#PBS -N spmv_weak
#PBS -q short_cpuQ
#PBS -l walltime=06:00:00
#PBS -l select=16:ncpus=8:mpiprocs=8:mem=50gb
#PBS -o logs/weak_output.log
#PBS -e logs/weak_error.log

# ==============================
# Load modules
# ==============================
module purge
module load gcc91
module load mpich-3.2.1--gcc-9.1.0

# ==============================
# Move to submission directory
# ==============================
cd $PBS_O_WORKDIR

# Create log directory
mkdir -p logs

# ==============================
# Run weak scaling script
# ==============================
chmod +x ./sh/run_weak_scaling.sh
./sh/run_weak_scaling.sh