#!/bin/bash
#PBS -N hybrid_weak_scaling
#PBS -q short_cpuQ
#PBS -l walltime=06:00:00
#PBS -l select=32:ncpus=8:mpiprocs=4:mem=50gb
#PBS -o logs/weak_output.log
#PBS -e logs/weak_error.log

module purge
module load gcc91
module load mpich-3.2.1--gcc-9.1.0

cd $PBS_O_WORKDIR
mkdir -p logs

export OMP_NUM_THREADS=2
export OMP_PROC_BIND=true
export OMP_PLACES=cores

chmod +x ./sh/run_weak_scaling.sh
./sh/run_weak_scaling.sh