#!/usr/bin/env python3
"""
===============================================================================
                SPARSE MATRIX-VECTOR RESULTS PARSER
===============================================================================

Description:
This script parses the execution time results of Sparse Matrix-Vector (SpMV)
simulations from the output .txt files generated by serial and parallel runs.
It focuses on extracting the P90 (90th percentile) execution times and standard
deviations (STD) for further analysis and visualization.

Supported Executions:
- SERIAL:          ser_<matrix_id>.txt
- SERIAL_IMP:      ser_imp_<matrix_id>.txt
- AUTO / AUTO_IMP: par_auto[_imp]_<threads>_<matrix>.txt
- SCHEDULES WITH CHUNK (static, guided, dynamic, runtime):
                   par_<schedule>_<threads>_<chunk>_<matrix>.txt

Main Features:
1. Extracts the P90 execution time in milliseconds from each results file.
2. Computes the standard deviation (STD) in milliseconds.
3. Organizes results into dictionaries for easy access:
   - ser      → {matrix_id: P90_time}
   - ser_imp  → {matrix_id: P90_time}
   - par      → {schedule: {threads: {matrix: {chunk: P90_time}}}}
4. Supports automatic iteration over all directories and files defined in DIRS.
5. Gracefully handles missing files or directories, printing warnings.

Dependencies:
- Python 3.x
- numpy

Usage:
- Import this script and call parse_results() to retrieve dictionaries with P90 timings:
    from this_script import parse_results
    ser, ser_imp, par = parse_results()

===============================================================================
"""

import os
import re
import numpy as np

# =============================
# RUTAS NUEVAS
# =============================
BASE = "../results"

DIRS = {
    "ser":         os.path.join(BASE, "ser"),
    "ser_imp":     os.path.join(BASE, "ser_imp"),
    "auto":        os.path.join(BASE, "par_auto"),
    "auto_imp":    os.path.join(BASE, "par_auto_imp"),
    "static":      os.path.join(BASE, "par_static"),
    "static_imp":  os.path.join(BASE, "par_static_imp"),
    "guided":      os.path.join(BASE, "par_guided"),
    "guided_imp":  os.path.join(BASE, "par_guided_imp"),
    "dynamic":     os.path.join(BASE, "par_dynamic"),
    "dynamic_imp": os.path.join(BASE, "par_dynamic_imp"),
    "runtime":     os.path.join(BASE, "par_runtime"),
    "runtime_imp": os.path.join(BASE, "par_runtime_imp"),
}

time_pattern = re.compile(r"Elapsed time\s*=\s*([0-9.eE+-]+)")

# ==========================================================
# EXTRAER P90
# ==========================================================
def extract_p90(path):
    if not os.path.exists(path):
        return None

    values = []
    with open(path, "r") as f:
        for line in f:
            m = time_pattern.search(line)
            if m:
                values.append(float(m.group(1)))

    if not values:
        return None

    return np.percentile(values, 90) * 1000.0

def extract_std(path):
    """Devuelve la desviación estándar (STD) en ms del archivo de tiempos"""
    if not os.path.exists(path):
        return None

    values = []
    with open(path, "r") as f:
        for line in f:
            m = time_pattern.search(line)
            if m:
                values.append(float(m.group(1)) * 1000.0)  # convertir a ms

    if not values:
        return None

    return np.std(values)



# ==========================================================
# PARSEADOR PRINCIPAL
# ==========================================================
def parse_results():

    ser = {}
    ser_imp = {}

    # schedules normales + imp
    par = {
        "auto": {},   "auto_imp": {},
        "static": {}, "static_imp": {},
        "guided": {}, "guided_imp": {},
        "dynamic": {}, "dynamic_imp": {},
        "runtime": {}, "runtime_imp": {},
    }

    # =============================
    # RECORRER TODAS LAS SUBCARPETAS
    # =============================
    for sched, folder in DIRS.items():
        if not os.path.isdir(folder):
            print("WARNING: carpeta no existe:", folder)
            continue

        for fname in os.listdir(folder):
            full = os.path.join(folder, fname)

            # =========================
            # SERIAL
            # =========================
            if sched == "ser":
                if m := re.match(r"ser_(\d+)\.txt", fname):
                    ser[int(m.group(1))] = extract_p90(full)
                continue

            if sched == "ser_imp":
                if m := re.match(r"ser_imp_(\d+)\.txt", fname):
                    ser_imp[int(m.group(1))] = extract_p90(full)
                continue

            # =========================
            # AUTO y AUTO_IMP
            # =========================
            if sched in ["auto", "auto_imp"]:
                if m := re.match(rf"par_{sched}_(\d+)_(\d+)\.txt", fname):
                    t = int(m.group(1))
                    d = int(m.group(2))
                    par[sched].setdefault(t, {})[d] = extract_p90(full)
                continue

            # =========================
            # SCHEDULES CON CHUNK
            # =========================
            if sched in ["static", "static_imp", "guided", "guided_imp",
                         "dynamic", "dynamic_imp", "runtime", "runtime_imp"]:

                if m := re.match(rf"par_{sched}_(\d+)_(\d+)_(\d+)\.txt", fname):
                    t = int(m.group(1))
                    c = int(m.group(2))
                    d = int(m.group(3))

                    par[sched].setdefault(t, {}).setdefault(d, {})[c] = extract_p90(full)
                continue

    return ser, ser_imp, par